-- in Supabase run these queries:
-- CREATE TABLE time_slots (
--     id SERIAL PRIMARY KEY,
--     day_of_week VARCHAR(10) NOT NULL,
--     start_time TIME NOT NULL,
--     end_time TIME NOT NULL,
--     includes_saturday BOOLEAN DEFAULT FALSE,
--     UNIQUE(day_of_week, start_time, end_time)
-- );
-- CREATE TABLE reservations (
--     id SERIAL PRIMARY KEY,
--     user_id UUID REFERENCES users(id),
--     guest_name VARCHAR(255),
--     time_slot_id INT NOT NULL REFERENCES time_slots(id),
--     reserved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     UNIQUE(user_id, time_slot_id),
--     UNIQUE(guest_name, time_slot_id)
-- );
-- INSERT INTO time_slots (day_of_week, start_time, end_time, includes_saturday)
-- VALUES
--     ('Friday', '16:00:00', '18:00:00', FALSE),
--     ('Friday', '18:00:00', '20:00:00', FALSE),
--     ('Friday', '20:00:00', '22:00:00', FALSE);
